# Generated by Django 2.2.6 on 2019-12-10 11:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('character', models.BooleanField(choices=[(False, '买家'), (True, '卖家')], default=False, verbose_name='身份')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('money', models.FloatField(default=0, verbose_name='账户余额')),
                ('address', models.CharField(default='', max_length=50, verbose_name='地址')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('image', models.TextField(verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30, verbose_name='商家名称')),
                ('buyer_name', models.CharField(max_length=30, verbose_name='买家名称')),
                ('thing_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('thing_photo', models.TextField(null=True, verbose_name='商品图片')),
                ('mobile', models.CharField(max_length=30, verbose_name='手机')),
                ('address', models.TextField(verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('state', models.CharField(max_length=30, null=True, verbose_name='状态')),
                ('num', models.PositiveIntegerField(verbose_name='商品数量')),
                ('one_price', models.FloatField(verbose_name='商品单价')),
                ('all_price', models.FloatField(verbose_name='订单总价')),
                ('thing_id', models.CharField(max_length=30, null=True, verbose_name='商品id')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='商品名称')),
                ('photo', models.TextField(verbose_name='商品图片')),
                ('introduce', models.TextField(verbose_name='商品简介')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('spare', models.PositiveIntegerField(verbose_name='商品库存')),
                ('state', models.BooleanField(default='', verbose_name='状态')),
                ('xiaoliang', models.PositiveIntegerField(verbose_name='商品销量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, verbose_name='标签')),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Sell')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='评论')),
                ('user', models.CharField(max_length=100, verbose_name='评论用户')),
                ('answer', models.TextField(null=True, verbose_name='回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Sell')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_id', models.CharField(max_length=30, null=True, verbose_name='商品')),
                ('num', models.PositiveIntegerField(verbose_name='数量')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='商品名称')),
                ('photo', models.TextField(verbose_name='商品图片')),
                ('introduce', models.TextField(verbose_name='商品简介')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('spare', models.PositiveIntegerField(verbose_name='商品库存')),
                ('xiaoliang', models.PositiveIntegerField(verbose_name='商品销量')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
